
.PHONY: all clean

all:
	g++ validator.cpp -D SUB1 -o sub1 -std=c++11 -O2 
	g++ validator.cpp -D SUB2 -o sub2 -std=c++11 -O2 
	g++ validator.cpp -D SUB3 -o sub3 -std=c++11 -O2 
	g++ validator.cpp -D SUB4 -o sub4 -std=c++11 -O2 
	g++ validator.cpp -D SUB5 -o sub5 -std=c++11 -O2 

clean:
	-rm sub?
